reviewers:
  defaults:
    - code-owners
  groups:
    code-owners:
      - Manav-Aggarwal
      - tzdybal
      - gupadhyaya
    rollkit:
      - S1nus
      - tuxcanfly
    devops:
      - smuu
      - sysrex
      - jrmanes
      - Bidon15
    celestia:
      - team:celestia
files:
  '**':
    - code-owners
    - rollkit
  '**/*Dockerfile':
    - devops
  '.github/**':
    - devops
options:
  ignore_draft: true
  ignored_keywords:
    - WIP
  number_of_reviewers: 3
