pull_request_rules:
  - name: backport patches to v0.11.x branch
    conditions:
      - base=main
      - label=backport:v0.11.x
    actions:
      backport:
        branches:
          - v0.11.x
  - name: backport patches to v0.10.x branch
    conditions:
      - base=main
      - label=backport:v0.10.x
    actions:
      backport:
        branches:
          - v0.10.x-lts
  - name: backport patches to v0.9.x branch
    conditions:
      - base=main
      - label=backport:v0.9.x
    actions:
      backport:
        branches:
          - v0.9.x-lts
