# lint runs all linters in this repository. This workflow is run on every pull
# request and push to main.
name: lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
        # This steps sets the GIT_DIFF environment variable to true
        # if files defined in PATTERS changed
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          # This job will pass without running if go.mod, go.sum, and *.go
          # wasn't modified.
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: v1.50.1
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
        if: env.GIT_DIFF

  # hadolint lints the Dockerfile
  hadolint:
    uses: celestiaorg/.github/.github/workflows/reusable_dockerfile_lint.yml@v0.1.1 # yamllint disable-line rule:line-length
    with:
      dockerfile: docker/mockserv.Dockerfile

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: celestiaorg/.github/.github/actions/yamllint@v0.1.1

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: celestiaorg/.github/.github/actions/markdown-lint@v0.1.1
