name: Build and Test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test & Coverage
      run: |
        go install github.com/ory/go-acc@v0.2.6
        go-acc -o coverage.txt ./... -- -v --race

    - uses: codecov/codecov-action@v2.1.0
      with:
        file: ./coverage.txt
