name: Build and Test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test & Coverage
      run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

    - uses: codecov/codecov-action@v2.1.0
      with:
        file: ./coverage.txt
